### ISSUE TITLE
Not updated to support Library Ferret 3.0.0

### ISSUE THREAD

**Issue by TalEdd** [jtorleon-studios-team/HUB-Medieval-entity#2]
Crashes on launch with new update to Library Ferret

**Comment by jtl-elisa** [comment]
Yes it's not already uploaded for support the new version, for the moment:
- library ferret 3.0.0
- - awesome dungeon
- - awesome dungeon end 
- - awesome dungeon ocean
- - awesome dungeon nether
- - better villages 
- - dungeon clusters 

all other mods must be updated to support the new version

**Comment by TalEdd** [comment]
Already updated all the other mods. I have all of them in a private modpack I am playing with. Love them all! ☺️
